// Code generated by protoc-gen-go. DO NOT EDIT.
// source: poster.proto

package pb3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bail struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Exdata               []byte    `protobuf:"bytes,2,opt,name=Exdata,proto3" json:"Exdata,omitempty"`
	Req                  *Bail_REQ `protobuf:"bytes,3,opt,name=Req,proto3" json:"Req,omitempty"`
	Ans                  *Bail_ANS `protobuf:"bytes,4,opt,name=Ans,proto3" json:"Ans,omitempty"`
	Error                int32     `protobuf:"varint,5,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Bail) Reset()         { *m = Bail{} }
func (m *Bail) String() string { return proto.CompactTextString(m) }
func (*Bail) ProtoMessage()    {}
func (*Bail) Descriptor() ([]byte, []int) {
	return fileDescriptor_6450fe10fba0fa72, []int{0}
}

func (m *Bail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bail.Unmarshal(m, b)
}
func (m *Bail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bail.Marshal(b, m, deterministic)
}
func (m *Bail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bail.Merge(m, src)
}
func (m *Bail) XXX_Size() int {
	return xxx_messageInfo_Bail.Size(m)
}
func (m *Bail) XXX_DiscardUnknown() {
	xxx_messageInfo_Bail.DiscardUnknown(m)
}

var xxx_messageInfo_Bail proto.InternalMessageInfo

func (m *Bail) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Bail) GetExdata() []byte {
	if m != nil {
		return m.Exdata
	}
	return nil
}

func (m *Bail) GetReq() *Bail_REQ {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *Bail) GetAns() *Bail_ANS {
	if m != nil {
		return m.Ans
	}
	return nil
}

func (m *Bail) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type Bail_REQ struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Able                 []int32  `protobuf:"varint,3,rep,packed,name=able,proto3" json:"able,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bail_REQ) Reset()         { *m = Bail_REQ{} }
func (m *Bail_REQ) String() string { return proto.CompactTextString(m) }
func (*Bail_REQ) ProtoMessage()    {}
func (*Bail_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_6450fe10fba0fa72, []int{0, 0}
}

func (m *Bail_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bail_REQ.Unmarshal(m, b)
}
func (m *Bail_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bail_REQ.Marshal(b, m, deterministic)
}
func (m *Bail_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bail_REQ.Merge(m, src)
}
func (m *Bail_REQ) XXX_Size() int {
	return xxx_messageInfo_Bail_REQ.Size(m)
}
func (m *Bail_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_Bail_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_Bail_REQ proto.InternalMessageInfo

func (m *Bail_REQ) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Bail_REQ) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Bail_REQ) GetAble() []int32 {
	if m != nil {
		return m.Able
	}
	return nil
}

type Bail_ANS struct {
	Password             string   `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bail_ANS) Reset()         { *m = Bail_ANS{} }
func (m *Bail_ANS) String() string { return proto.CompactTextString(m) }
func (*Bail_ANS) ProtoMessage()    {}
func (*Bail_ANS) Descriptor() ([]byte, []int) {
	return fileDescriptor_6450fe10fba0fa72, []int{0, 1}
}

func (m *Bail_ANS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bail_ANS.Unmarshal(m, b)
}
func (m *Bail_ANS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bail_ANS.Marshal(b, m, deterministic)
}
func (m *Bail_ANS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bail_ANS.Merge(m, src)
}
func (m *Bail_ANS) XXX_Size() int {
	return xxx_messageInfo_Bail_ANS.Size(m)
}
func (m *Bail_ANS) XXX_DiscardUnknown() {
	xxx_messageInfo_Bail_ANS.DiscardUnknown(m)
}

var xxx_messageInfo_Bail_ANS proto.InternalMessageInfo

func (m *Bail_ANS) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Bail)(nil), "pb3.Bail")
	proto.RegisterType((*Bail_REQ)(nil), "pb3.Bail.REQ")
	proto.RegisterType((*Bail_ANS)(nil), "pb3.Bail.ANS")
}

func init() { proto.RegisterFile("poster.proto", fileDescriptor_6450fe10fba0fa72) }

var fileDescriptor_6450fe10fba0fa72 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xc9, 0xa6, 0x5d, 0xdc, 0x71, 0xbd, 0x04, 0x91, 0xd0, 0x8b, 0xd1, 0x53, 0x4f, 0x39,
	0xd8, 0x5f, 0x50, 0x25, 0xd7, 0xc5, 0xce, 0xe2, 0x0f, 0x48, 0x68, 0x0e, 0xc2, 0xda, 0xc4, 0xa4,
	0xa0, 0x47, 0x7f, 0xba, 0x4c, 0x2a, 0x85, 0x7a, 0x9b, 0x8f, 0x37, 0x2f, 0x79, 0x6f, 0xe0, 0x18,
	0x43, 0x9e, 0x7d, 0xd2, 0x31, 0x85, 0x39, 0x08, 0x1e, 0x5d, 0xf7, 0xf8, 0xb3, 0x83, 0xea, 0xd9,
	0xbe, 0x5f, 0x84, 0x80, 0xea, 0x25, 0x8c, 0x5e, 0x32, 0xc5, 0xda, 0x1a, 0xcb, 0x2c, 0xee, 0x60,
	0x6f, 0xbe, 0x47, 0x3b, 0x5b, 0xb9, 0x53, 0xac, 0x3d, 0xe2, 0x1f, 0x89, 0x7b, 0xe0, 0xe8, 0x3f,
	0x25, 0x57, 0xac, 0xbd, 0x7e, 0xba, 0xd1, 0xd1, 0x75, 0x9a, 0xde, 0xd0, 0x68, 0x06, 0x24, 0x85,
	0x16, 0xfa, 0x29, 0xcb, 0xea, 0xff, 0x42, 0x7f, 0x3a, 0x23, 0x29, 0xe2, 0x16, 0x6a, 0x93, 0x52,
	0x48, 0xb2, 0x2e, 0xdf, 0x2d, 0xd0, 0x0c, 0xc0, 0xd1, 0x0c, 0xa2, 0x81, 0xab, 0xb7, 0xec, 0xd3,
	0x64, 0x3f, 0x96, 0x38, 0x07, 0x5c, 0x99, 0xb4, 0x57, 0x9b, 0xf3, 0x57, 0x48, 0x63, 0x09, 0x75,
	0xc0, 0x95, 0xa9, 0x82, 0x75, 0x17, 0x2f, 0xb9, 0xe2, 0x54, 0x81, 0xe6, 0xe6, 0x01, 0x78, 0x7f,
	0x3a, 0x6f, 0x6c, 0x6c, 0x6b, 0x73, 0xfb, 0x72, 0x8e, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0x79,
	0x73, 0xf2, 0xf9, 0x1e, 0x01, 0x00, 0x00,
}
